apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-pipeline-app
  labels:
    app: devops-pipeline-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-pipeline-app
  template:
    metadata:
      labels:
        app: devops-pipeline-app
    spec:
      containers:
        - name: devops-pipeline-app-container
          image: kaveeshadev/devops-pipeline-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
