apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-pipeline-app
  labels:
    app: devops-pipeline-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-pipeline-app
  template:
    metadata:
      labels:
        app: devops-pipeline-app
    spec:
      containers:
        - name: devops-pipeline-app-container
          image: kaveeshadev/devops-pipeline-app:latest
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
