apiVersion: v1
kind: Service
metadata:
  name: devops-pipeline-app-service
spec:
  type: NodePort
  selector:
    app: devops-pipeline-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30007
